### ISSUE TITLE
After updating to 1.0 stable release, classes not appended to menu links.

### ISSUE THREAD

**Issue by eric-schmidt** [yannickoo/menu_link_attributes#38]
After updating to 1.0 stable, custom classes that have been added to menu items are not being rendered on menu items when viewing the site.

**Comment by dalin-** [comment]
Same here. 

Re-saving the menu items doesn't resolve the problem.

**Comment by andrewkamm** [comment]
I've just installed 1.0 fresh (no previous version) and am having the same issue.

**Comment by yannickoo** [comment]
Oh no :( I think this has been caused by #30.

Which version of Drupal 8 you are using exactly?

**Comment by dalin-** [comment]
This site is currently on  8.3.7.

**Comment by yannickoo** [comment]
Are you using the core menu blocks or another contrib module for displaying menus @dalin-?

**Comment by weseze** [comment]
Seems to be caused by these lines:

<pre>    // Apply container attributes on &gt;li> element.
    if ($options && isset($options['container_attributes'])) {
      foreach ($options['container_attributes'] as $attribute => $value) {
        $item['attributes']->setAttribute($attribute, $value);
      }
    }</pre>

If I replace it with the below code everything works again. (but the classes are added on the li element and no longer on the a element... But it is workable.

<pre>    // Apply container attributes on &gt;li> element.
    if ($options && isset($options['attributes'])) {
      foreach ($options['attributes'] as $attribute => $value) {
        $item['attributes']->setAttribute($attribute, $value);
      }
    }</pre>

I've attached a patch file (as txt becayse github won't allow patch files) Would be really great if you enabled the issue queue on your drupal org project page. I could then upload the patch there and have it in my composer workflow.

[menu_link_attributes-classes_not_appended_to_menu_links-38-d8.patch.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/1457489/menu_link_attributes-classes_not_appended_to_menu_links-38-d8.patch.patch.txt)

**Comment by dalin-** [comment]
@yannickoo

> Are you using the core menu blocks or another contrib module for displaying menus @dalin-?

This block is just the plain menu block.  This site is also using Menu Block module, but none of its advanced features are enabled on the blocks in question

**Comment by jodyHamilton** [comment]
I had to set my composer file to use 1.0.0-beta3 to get the module working

**Comment by ghost** [comment]
This is a bit odd; first of all this issue-queue should be on drupal.org so we could properly assist in fixing the module because **it is broken**.
As @jodyHamilton  states correctly you need to downgrade to beta3 to get it working. 
Using latest Core 8.5.2 together with admin-toolbar and admin-toolbar extra-tools without any other menu-related modules. Clean install fails. Clean install of beta-3 succeeds.
So @yannickoo this should get some prio.

**Comment by kevinquillen** [comment]
This should all be happening on drupal.org so we can get patches and contribute them and use them in composer based workflows. Otherwise its broken...

**Comment by yannickoo** [comment]
We are now managing the issues on drupal.org since it also allows forking now 💪 Feel free to [create](https://www.drupal.org/node/add/project-issue/menu_link_attributes) a new issue if you are still experiencing this.
